SWP\Component\OutputChannel\Model\OutputChannel:
    exclusion_policy: ALL
    properties:
        config:
            expose: true
            groups: [api]
            type: array
        type:
            expose: true
            groups: [api]
            type: string
